### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/EllaTheGame#2]

**Comment by damiansikora85** [comment]
I will look at this one

**Comment by damiansikora85** [comment]
Hey, could you explain a bit what you expect to be done in this issue? Do you need to publish builds somewhere or just simple make a build on Travis? Right now I'm able to successfully build a windows version.

**Comment by CrazyMarvin** [comment]
That are good news. 😊

Possible outputs are
- GitHub Releases
- FTP Upload 
- itch.io
- Google Play
- App Store

Formats are
- Installers/standalone versions for Windows, Linux and macOS
- WebGL
- .apk
- .ipa

I don't have an Apple Developer account though. 
Regarding itch.io @avivajpeyi might be working in #9 on it.

Notifications on Slack and Telegram would be nice too.

I am open for other ideas. What do you think?

**Comment by damiansikora85** [comment]
This looks fine for me. So I will upload builds to GitHub Releases then. I also don't have Apple Developer account so I'm afraid I cannot handle iOS builds but rest of them should not be a problem. 
Do you have a specific Slack channel for notifications?

Other think to do with TravisCI could be run unit tests but first need to create some :)

**Comment by CrazyMarvin** [comment]
I opened an issue for unit tests (#11).

Regarding Slack, there is already a channel. How does the integration work?

**Comment by CrazyMarvin** [comment]
We will go with GitHub Actions (see #9) instead of Travis.
