### ISSUE TITLE
Target Android 14

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/EllaTheGame#70]
It would be nice to target Android 14 because it will be required from Google Play soon.

**Comment by avoxaya** [comment]
Hello, Can you explain what we as contributors have to do about this issue in brief. I am sorry I am new to this and could use some help understanding this issue.

**Comment by CrazyMarvin** [comment]
> Hello, Can you explain what we as contributors have to do about this issue in brief. I am sorry I am new to this and could use some help understanding this issue.

We need to create a release artifact that targets Android 14 (API 34). That is not possible at the moment because some dependencies like Yodo1 don't support it yet.

**Comment by CrazyMarvin** [comment]
Are you interested to support us, @avoxaya? What are your interests?

**Comment by CrazyMarvin** [comment]
Version 32 targets Android 14. 🥳
